"""
Engineer Agent — LaunchMind

Responsibilities:
    - Read the product specification from the Product agent.
    - Generate an HTML landing page based on the spec.
    - Create a GitHub issue describing the work.
    - Commit the landing page code to a new feature branch.
    - Open a pull request for review.
"""

import json
import logging
import os

from core.llm import call_llm
from core.message_bus import MessageBus
from integrations.github_integration import GitHubIntegration

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are a senior frontend engineer. Given a product specification, generate a complete, professional HTML landing page.

The page MUST include:
- A hero section with the product name as headline and the value proposition as subheadline
- A features section highlighting all key features with icons or styled cards
- A user personas/testimonials section
- A call-to-action button with compelling text
- A footer with copyright
- Professional, modern CSS styling in a <style> block (use gradients, shadows, good typography)
- Mobile-responsive design using media queries
- The full HTML document starting with <!DOCTYPE html>

Return ONLY the raw HTML content. No markdown fences, no explanation, no extra text."""

ISSUE_PROMPT = """Given this product spec, write a brief GitHub issue description for creating the landing page.
Return ONLY a JSON object with keys: title (string), body (string in markdown).
Product: {spec}"""

PR_PROMPT = """Given this product spec, write a pull request title and description for the landing page.
Return ONLY a JSON object with keys: title (string), body (string in markdown).
Product: {spec}"""


class EngineerAgent:
    """Generates code artifacts and manages GitHub workflow."""

    def __init__(self, message_bus: MessageBus):
        self.name = "engineer"
        self.message_bus = message_bus
        self.github = GitHubIntegration()

    def run(self) -> None:
        """
        Execute the Engineer agent's workflow.

        Reads the product spec, generates HTML, and pushes to GitHub.
        """
        messages = self.message_bus.receive(self.name)
        if not messages:
            logger.warning("Engineer agent: no messages to process.")
            return

        msg = messages[-1]
        logger.info(f"Engineer agent received {msg.message_type.value} from {msg.from_agent}")

        spec = msg.payload.get("spec", msg.payload)

        # Build prompt based on message type
        if msg.message_type.value == "revision_request":
            feedback = msg.payload.get("feedback", {})
            issues = feedback.get("issues", []) if isinstance(feedback, dict) else [str(feedback)]
            user_prompt = (
                f"The previous landing page was rejected by QA. Issues found:\n"
                + "\n".join(f"- {i}" for i in issues)
                + f"\n\nProduct spec: {json.dumps(spec, indent=2)}\n\n"
                "Please generate an improved landing page addressing all issues."
            )
        else:
            user_prompt = f"Product specification:\n{json.dumps(spec, indent=2)}"

        # Generate HTML landing page
        try:
            html_content = call_llm(SYSTEM_PROMPT, user_prompt, json_mode=False)
            # Strip markdown fences if the model wraps them
            if html_content.strip().startswith("```"):
                lines = html_content.strip().split("\n")
                html_content = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])
            logger.info("Engineer agent generated HTML landing page.")
        except Exception as e:
            logger.error(f"Engineer agent LLM call failed: {e}")
            self._send_error(msg, str(e))
            return

        # Save HTML locally
        os.makedirs("outputs", exist_ok=True)
        with open("outputs/landing_page.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        logger.info("Saved landing page to outputs/landing_page.html")

        # GitHub workflow
        product_name = spec.get("product_name", "LaunchMind Product")
        branch_name = "feature/landing-page"

        # Create issue
        try:
            issue_data = call_llm("Return ONLY valid JSON.", ISSUE_PROMPT.format(spec=json.dumps(spec)), json_mode=True)
        except Exception:
            issue_data = {"title": f"Landing page for {product_name}", "body": "Auto-generated by EngineerAgent."}

        issue_result = self.github.create_issue(
            title=issue_data.get("title", f"Landing page for {product_name}"),
            body=issue_data.get("body", "Auto-generated."),
            labels=["agent-generated"],
        )

        # Create branch
        branch_result = self.github.create_branch(branch_name)

        # Commit HTML file
        commit_result = self.github.commit_file(
            branch=branch_name,
            file_path="index.html",
            content=html_content,
            message=f"Add landing page for {product_name}",
        )

        # Open PR
        try:
            pr_data = call_llm("Return ONLY valid JSON.", PR_PROMPT.format(spec=json.dumps(spec)), json_mode=True)
        except Exception:
            pr_data = {"title": f"Landing page: {product_name}", "body": "Auto-generated landing page."}

        pr_result = self.github.create_pull_request(
            title=pr_data.get("title", f"Landing page: {product_name}"),
            body=pr_data.get("body", "Auto-generated."),
            head=branch_name,
        )

        # Extract info for result
        pr_url = pr_result.get("html_url", "")
        pr_number = pr_result.get("number", 0)
        issue_url = issue_result.get("html_url", "")
        commit_sha = commit_result.get("commit", {}).get("sha", "") if "commit" in commit_result else ""

        result_payload = {
            "html": html_content,
            "pr_url": pr_url,
            "pr_number": pr_number,
            "issue_url": issue_url,
            "commit_sha": commit_sha,
            "branch": branch_name,
        }

        result_msg = self.message_bus.create_message(
            from_agent=self.name,
            to_agent="ceo",
            message_type="result",
            payload=result_payload,
            parent_message_id=msg.message_id,
        )
        self.message_bus.send(result_msg)
        logger.info(f"Engineer agent done. PR: {pr_url}, Issue: {issue_url}")

    def _send_error(self, original_msg, error_text: str) -> None:
        error_msg = self.message_bus.create_message(
            from_agent=self.name,
            to_agent="ceo",
            message_type="result",
            payload={"error": error_text},
            parent_message_id=original_msg.message_id,
        )
        self.message_bus.send(error_msg)
